#ifndef SOCCER_DEFINES_H
#define SOCCER_DEFINES_H

#define SOCCER_FIELD_SIZE 60.0
#define SOCCER_MAX_ANGLE 180
#define TRAIN_REWARD 1
#define TEST_REWARD 2
#define BASE_PORT 7000
#define TRAIN_PHASE 0
#define VALIDATION_PHASE 1
#define TEST_PHASE 2
#define PLAY_PHASE 3
#define SINGLE_EVAL_PHASE 4
#endif
